### PR TITLE
Docker compose

### PR DESCRIPTION
**Pull request by dulhaver**
removed full stops from the end of bullet point lines.
I think this makes it less likely to copy'n'paste incorrect commands (including the full stops)

### CODE REVIEW

**Comment by ianneub** [comment]
Thanks for the updates. I'd be happy to merge this but it is showing merge conflicts. Can you please rebase your branch against the current code?

**Comment by dulhaver** [comment]
I saw that, unfortunately I seem not to be all to git proficient and 
don't really now how to do that ... I'll figure something out and then 
get back to you

sorry for the hassle

**Comment by ianneub** [comment]
No problem @vrms ! I was able to resolve the conflicts through GitHub and merge the code. Thanks for the contribution.

**Comment by dulhaver** [comment]
ok, great. thanks

**Pull request merged**
